### ISSUE TITLE
hapinode timekeeping

### ISSUE THREAD

**Issue by james-prior** [mayaculpa/hapi#75]
@ozarchie wrote:

> Hi James,
> I was just wondering if I could ask you to look at the time
> functions for the hapinode? At present, I read the time (epoch)
> using ntp from the mqtt server (which presumably has the right
> time). The code in loop() then maintains the epoch value by
> incrementing each time through the loop. This is rather
> inaccurate. I believe that arduino has a Time library that takes
> a "syncserver" (ntp) and maintains the correct time. I guess it
> does this via interrupts in the background. It would be far more
> accurate for us if we could use this method for reporting and
> time-keeping. Especially, if we can then use the extended time
> functions for scheduling e.g. lamps, pumps etc 
> Cheers John

I will look at it.

So far, my understanding of the hapi arduino code and the Arduino
way of doing things is pretty feeble. I have just been refactoring 
low hanging fruit, which eventually leads to a better understanding.
I have played with Arduinos a little bit, but I don't know the details of 
Arduino's ways of doing things. I have been bitten by some things
they do, hence the caution warnings about some of the Arduino things I do.
One that amuses me in its crudeness is that it seems that Arduino
uses something not much more sophisticated than [cat](https://en.wikipedia.org/wiki/Cat_%28Unix%29) 
as the linker/locater.

Things I always look for with free running timers, is what happens
when they wrap-around or overflow. I pay attention to the size of 
timers and whether they are signed or unsigned.

I expect that there are some things that need to happen,
such as doing something at sunrise, that can tolerate
doing them a few minutes early or late without any problem.
Other things, like dithering the opening and closing of an 
on/off valve to get flow between nothing and full blast,
take careful real-time care. Which things fit in each category
or tolerant of sloppy timekeeping versus strict, fast real-time?

By the way, Bresenham's algorithm is great for dithering things
in the time domain, not just drawing lines.

**Comment by james-prior** [comment]
How often do you want to call getNTPTime?
What frequency do you want the LED to flash?

**Comment by james-prior** [comment]
How often do you want hapiSensors() to be called?

**Comment by TylerReedMC** [comment]
One thing I've thought about in the past is having an SM send out a time beacon every so often, or on-demand. Not a great solution though. A better solution might be to embed an RTC with the Node like we've done on the Smart Module. It's a $1 solution. It could also alter the enclosure design, so if the RTC is a potential solution we should discuss it sooner rather than later.

**Comment by TylerReedMC** [comment]
On the LED, if would be great if the flash rate were user-definable. The more it flashes, the larger the solar panel and battery we'll need.

**Comment by ozarchie** [comment]
Hi James, a difficult design question. In the case of peristaltic pumps we
want high accuracy from pH and TDS. In the case of a sodiim vapor lamp, the
lux will take some time to stabilize. Maybe this is a variable that should
be in ControlData. What do you think? Cheers Archie

**Comment by ozarchie** [comment]
Hi James, I am not sure about the accuracy of the time library.  I think
that as long as the time is within 10 seconds that it would be great. So a
refresh from ntp that maintains 10s accuracy.
The LED flash should be about 1s every 10s. In the future we may want to
run the node using battery and every joule will matter.  Cheers Archie

**Comment by james-prior** [comment]
OK. So it looks like it's time for a bigger change to time code;
that my littler refactorings, that nibble around the edges will not suffice.
Bigger changes will definitely break stuff, so I need to run the code
for my own local testing.
I have a couple of UNO r3 board, one Pro Mini 5V board,
and a genuine Arduino MEGA 2560 r3 with
a genuine Arduino MEGA Sensor Shield.
What's the minimum hardware I need to acquire to run the Arduino code?

**Comment by TylerReedMC** [comment]
Your Mega and an Ethernet shield would suffice, I would think.

**Comment by james-prior** [comment]
Earlier I wrote: 

> OK. So it looks like it's time for a bigger change to time code;
> that my littler refactorings, that nibble around the edges will not suffice.

I did a bunch of big changes, so in addition to cleaning up code and fixing bugs,
I would also create new ones. I don't have the requisite hardware yet,
so I am punting back to little refactorings. I looked at it yesterday and
saw some obvious low hanging fruit.

**Comment by james-prior** [comment]
@ozarchie wrote,

> In the case of peristaltic pumps we want high accuracy from pH and TDS.
> In the case of a sodiim vapor lamp, the lux will take some time to stabilize.
> Maybe this is a variable that should be in ControlData. What do you think?

Does that have to do with timekeeping?

**Comment by james-prior** [comment]
I cleaned up the incrementing of epoch from loop() in pull request #94.
It should be as accurate as millis().

I am not comfortable with changing epoch two ways:
- frequent increments
- occasional getNTPTime() calls

I fear that changing epoch those two ways
would occasionally lead to epoch not being monotonic,
that epoch could jump backwards occasionally.

**Comment by james-prior** [comment]
I implemented many changes to timekeeping. See pull request #95.
It needs testing.

I am working towards having the CPU sleep to save power
when there is nothing useful to do.

**Comment by james-prior** [comment]
@TylerReedMC wrote:

> Your Mega and an Ethernet shield would suffice, I would think.

An ethernet shield was over $30 at Microcenter.
Would an [Adafruit HUZZAH ESP8266 Breakout board](http://www.microcenter.com/product/458078/HUZZAH_ESP8266_Breakout) suffice? It is only $10.

**Comment by ozarchie** [comment]
Hi James,

While I think the Huzzah product will be OK for development, I strongly
suggest that you use the device in this page :-
https://github.com/ozarchie/hapi/wiki/HAPInode or any ESP32 based device
e.g. (
http://www.ebay.com/itm/ESP-32S-ESP32-Development-Board-2-4GHz-Dual-Mode-WiFi-Bluetooth-Antenna-Module-/201853283621?hash=item2eff64ad25:g:ArkAAOSwax5Y1OV3)
This device is only USD8 with free shipping . The ESP32 has many advantages
over the ESP8266, which is limited to one analog channel. As we bring more
devices online (pH, RDS, lux) this would be a severe limitation for
development and testing. The ESP32 also has BLE which is ideal for
communicating with low power use devices that can be run on button
batteries and are paired to a specific node. TI has a great SensorTag for
development of such devices. http://www.ti.com/tool/cc2650stk

However, the ESP8266 is very cheap and may be used in single sensor/
control situations.

I will start testing the time changes this weekend.

There are two issues with time as you have identified.
The first is the actual time. This is currently set using ntp and the value
epoch is maintained.
Instead of maintaining epoch, as Tyler has suggested, we could also add a
DS3231 module (<$1) and synchronise that using ntp from the mqtt broker.

The second is the delay() function. As these devices may be used with LiPo
batteries, we want the code to be electron efficient. Arduino has a simple
timer e.g. http://playground.arduino.cc/Code/SimpleTimer which does not use
sleep mode. Other libraries are available that do sue sleep mode e.g.
https://github.com/n0m1/Sleep_n0m1 . However, I have not yet had the time
to verify that they work across mega2560, ESP8266 and ESP32.

LOts of fun testing ahead ..

Cheers
Archie

**Comment by captainigloo** [comment]
Hi all,
Do you know Z-wave technology? I use the **Z-Uno** (Arduino Z-wave: https://z-uno.z-wave.me/technical/) in my projects. Considerable configuration of sensors can be envisaged. It is expensive and it does not correspond to the specifications of the project, but it is good to know ...
![z-uno](https://cloud.githubusercontent.com/assets/2509833/26751801/b2307e08-4842-11e7-8c2a-fc702e8837e8.jpg)

**Comment by ozarchie** [comment]
Hi James,
Regarding "I fear that changing epoch those two ways
would occasionally lead to epoch not being monotonic,
that epoch could jump backwards occasionally.".
I think we can get around this concern by using a two stage update. I agree that monotonicity is important. We can delay the update of the local time by checking the difference with the ntp time. Let's say the ntp time is five seconds behind. If we simply overwrote the local epoch, then some comparisons would be negative. But if we know the local time is five seconds ahead of the true time.  We can simply 'stretch' the update of the local epoch for a total of 5 seconds i.e. when the time to update based on the mS counter comes around , we decrement the difference (5) and skip the update of the local epoch value. We continue to do this until the difference is zero. We can do this every 10s so that the 5s difference is not too long a pause. Similarly, if the ntp is 5s ahead, we simply add 2s when we update the local epoch. At the point that the difference goes to zero, we can update any local hardware e.g. RTC devices.
What do you think?

**Comment by herrold** [comment]
z-wave is interesting, but it is not clear now 'Open Source' it is ...

http://www.techhive.com/article/3114232/home-tech/z-wave-part-of-it-at-least-becomes-an-open-smart-home-standard.html

The 'take-away' from that article is:

> While hobbyists will be free to do whatever they wish with the Z-Wave standard, any developer or manufacturer who desires to have their commercial products labeled as Z-Wave Certified will need to join the Z-Wave Alliance and submit their products for testing

The originator of that product line has 'sort of' open sourced, PART of it:

http://www.sigmadesigns.com/news/sigma-designs-releases-z-wave-interoperability-layer-into-the-public-domain/

and there are some truly Open S4ouce _connectors_:

https://github.com/OpenZWave/

And a seemingly different reverse-engineering of the protocol:

http://www.openzwave.com/

...  if a self-organizing local network within which to distribute time data is the goal,, there are other 'free-er' routes

**Comment by TylerReedMC** [comment]
Thanks Russ. It looks interesting. What benefits does it have over 802.11N?

**Comment by captainigloo** [comment]
Hi all,
To be clear, I do not understand the goal of having several network nodes in IP on lite platforms like ESP for example, and then an application hub with the Pi-Zero to make the MQTT gateway with the cloud.
Knowing that each node can reach only the MQTT cloud. I think I've read the basics on the Wiki, but I'm a little lost. I did not find a technical architecture diagram but only the functional diagram.
Similarly, why the nodes must have RTC/NTP synchronization while the server cloud record the time series on the Epoch of the server.
Why do nodes "push" on a time synchronization instead of "polling" the server?
Sorry for my English.

**Comment by ozarchie** [comment]
I think it relates to resilience. Sometimes the cloud is not available, sometimes the local broker is not available. The nodes can continue to collect data based on their own (synchronised) time and later upload to the PiZ gateway and then, the cloud. The PiZ can easily run a local database for both analysis and control. The cloud is for extensive analytics and extensive control.

**Comment by TylerReedMC** [comment]
Great questions Sebastien. To Archie's point, I think it's primarily a question of scalability and fault-tolerance. From a scalability standpoint, assume we have 10 facilities with 200 sensors in each facility. If all nodes connected directly to a cloud server, we would need to be able to handle 2000 simultaneous secure connections at the cloud-based broker. Traffic between nodes within a single facility would have to pass over the internet and if the internet connection fails, nodes that are side-by-side couldn't communicate. Dependence on an internet connection for time-stamping is also vulnerable to failure. The idea is to have all sensor readings time-stamped with the "truest" time-stamp possible (i.e closest to the hardware) so that the data can be subjected to a "store-and-forward" type of communications process without losing data integrity.

**Comment by captainigloo** [comment]
Ok it's clear.

Ok, if each node did a data retention this would avoid delivering in continuous flow, but you actually need an embedded time reference. 
I am not an aficionados of IoT WiFi, I prefer the technologies at frequencies below 1000Mhz because of the performance of range and penetration. Certainly the bit rates are lower but more robust than 2.4Ghz.

**Comment by ozarchie** [comment]
Hi Sébastien, I agree. I would like to see if we can do this with the ESP
devices -:
https://1technophile.blogspot.com.au/2016/04/433tomqttto433-bidirectional-gateway.html

**Comment by TylerReedMC** [comment]
All piZ modules have embedded real-time clocks (RTC). When a module boots, it will check for NTP services. If an NTP service is available, it gets the current time and updates its system time and RTC. If an NTP service is not available, it sets the system time from its RTC.  

Archie can best explain the time management side of the HAPI Nodes.

**Comment by ozarchie** [comment]
It is similar, except that the only NTP service that the HAPInode looks for is from mqttbroker.local. After the initial boot, it looks once a day (at 3.30am) to see if it can update its RTC.

**Comment by captainigloo** [comment]
Yes I know this type of configuration with a chip/hat RTC over the Pi.
Ideally, and to be certain not to lose data, the PiZ should be the Wifi access point in repeater mode ?

**Comment by captainigloo** [comment]
Then the nodes must have an NTP service embedded by the PiZ on the local network. At the connection on the local network the nodes must synchronize on the PiZ which is autonomous to him with his chipset RTC.

**Comment by james-prior** [comment]
The recent acceptance of pull requests likely addresses this issue,
so I am closing it.
